name       : vkbasalt
version    : 0.3.2.9
release    : 3
source     :
    - https://github.com/DadSchoorse/vkBasalt/archive/refs/tags/v0.3.2.9.tar.gz : f13ff6e8f05218800f0fb516f927983170d5ad4dc661ad671bc1fbc436d53b46
license    : Zlib
component  : system.utils
summary    : vkBasalt is a Vulkan post processing layer to enhance the visual graphics of games, similar to SweetFX/ReShade.
description: |
    vkBasalt is a Vulkan post processing layer to enhance the visual graphics of games. Currently, the build in effects are: Contrast Adaptive Sharpening, Denoised Luma Sharpening, Fast Approximate Anti-Aliasing, Enhanced Subpixel Morphological Anti-Aliasing, 3D color LookUp Table. It is also possible to use Reshade Fx shaders and it can be easily configured using GOverlay.
emul32     : yes
libsplit   : no
patterns   :
    - /*
builddeps  :
    - pkgconfig32(x11)
    - glslang-32bit-devel
    - spirv-headers
    - vulkan-headers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
