name       : vkbasalt
version    : 0.3.2.2
release    : 1
source     :
    - https://github.com/DadSchoorse/vkBasalt/releases/download/v0.3.2.2/vkBasalt-0.3.2.2.tar.gz : dd2c714b3569d5da0bc2f058d85cfc7683c8a9bc6d6255b80b3e968c902e1913
license    : Zlib
component  : system.utils
summary    : vkBasalt is a Vulkan post processing layer to enhance the visual graphics of games, similar to SweetFX/ReShade.
description: |
    vkBasalt is a Vulkan post processing layer to enhance the visual graphics of games. Currently, the build in effects are: Contrast Adaptive Sharpening, Denoised Luma Sharpening, Fast Approximate Anti-Aliasing, Enhanced Subpixel Morphological Anti-Aliasing, 3D color LookUp Table. It is also possible to use Reshade Fx shaders and it can be easily configured using GOverlay.
emul32     : yes
libsplit   : no
patterns    : 
    - /*
builddeps  : 
    - pkgconfig32(x11)
    - glslang-32bit-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
