name       : vkbasalt
version    : 0.3.2.5
release    : 2
source     :
    - https://github.com/DadSchoorse/vkBasalt/archive/refs/tags/v0.3.2.5.tar.gz : 837cf63737302de7ab9c4a190a1ed3b8a1174630d3753f7a8478b140294b3b39
license    : Zlib
component  : system.utils
summary    : vkBasalt is a Vulkan post processing layer to enhance the visual graphics of games, similar to SweetFX/ReShade.
description: |
    vkBasalt is a Vulkan post processing layer to enhance the visual graphics of games. Currently, the build in effects are: Contrast Adaptive Sharpening, Denoised Luma Sharpening, Fast Approximate Anti-Aliasing, Enhanced Subpixel Morphological Anti-Aliasing, 3D color LookUp Table. It is also possible to use Reshade Fx shaders and it can be easily configured using GOverlay.
emul32     : yes
libsplit   : no
patterns   :
    - /*
builddeps  :
    - pkgconfig32(x11)
    - glslang-32bit-devel
    - spirv-headers
    - vulkan-headers
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
